/*==================================================================================================
*   Project              : RTD AUTOSAR 4.7
*   Platform             : CORTEXM
*   Peripheral           : CANEXCEL
*   Dependencies         : 
*
*   Autosar Version      : 4.7.0
*   Autosar Revision     : ASR_REL_4_7_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 2.0.1
*   Build Version        : S32ZE_RTD_2_0_1_D2505_ASR_REL_4_7_REV_0000_20250508
*
*   Copyright 2021-2025 NXP
*
*   NXP Confidential and Proprietary. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/
/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef CANEXCEL_IP_SA_INIT_PBCFG_H
#define CANEXCEL_IP_SA_INIT_PBCFG_H
/**
*   @file CanEXCEL_IP_PBcfg.h
*
*   @addtogroup CanEXCEL
*   @{
*/
#ifdef __cplusplus
extern "C"{
#endif
/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
/*
* @file           CanEXCEL_Ip_Sa_Init_PBcfg.h
*/
#define CANEXCEL_IP_SA_VENDOR_ID_INIT_PBCFG_H                     43
#define CANEXCEL_IP_SA_AR_RELEASE_MAJOR_VERSION_INIT_PBCFG_H      4
#define CANEXCEL_IP_SA_AR_RELEASE_MINOR_VERSION_INIT_PBCFG_H      7
#define CANEXCEL_IP_SA_AR_RELEASE_REVISION_VERSION_INIT_PBCFG_H   0
#define CANEXCEL_IP_SA_SW_MAJOR_VERSION_INIT_PBCFG_H              2
#define CANEXCEL_IP_SA_SW_MINOR_VERSION_INIT_PBCFG_H              0
#define CANEXCEL_IP_SA_SW_PATCH_VERSION_INIT_PBCFG_H              1
/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/
#define CANEXCEL_IP_INIT_SA_PB_CFG \
extern const Canexcel_Ip_ConfigType CanXL_Config0; \
extern const Canexcel_Ip_ConfigType CanXL_Config1; 
#define INST_INIT_CANEXCEL_0 0U
#define INST_INIT_CANEXCEL_1 1U
#define CANEXCEL_IP_INIT_SA_STATE_PB_CFG \
extern Canexcel_Ip_StateType CanEXCEL_Init_State0; \
extern Canexcel_Ip_StateType CanEXCEL_Init_State1; 
#ifdef __cplusplus
}
#endif /* __cplusplus */

/** @} */

#endif /* CANEXCEL_IP_PBCFG_H */

